import { utilService } from '../../../services/util-service.js';



const gMails = [
    {
        id: utilService.makeId(),
        subject: 'Don’t forget your 30 days FREE Access to Udacity',
        from: 'support@udacity.com',
        to: 'alex207@gmail.com',
        body: 'Ti‍me is running out on this special offer. Act n‍ow to get 3‍0 da‍ys Free Access to the Udacity Nanodegree program of your choice. Choose from 60+ programs that can help you increase your earning potential and take your tech career to the next level.Our graduates’ success speaks for itself. In fact, 73% of our graduates reported a favorable career change in the first 1‍2 mon‍ths after completing their Nanodegree program. And they report an average raise of 24%! Our stellar ratings show just how valuable Udacity can be if you’re trying to land a successful tech job or upskill. See below and explore our ratings across the board. Then check out our catalog and see which of our 60+ programs you’d like 3‍0 da‍ys Free Access to. There is no obligation to continue so you have nothing to lose and everything to gain. Get started tod‍ay!',
        isSend: false,
        isRead: true,
        isFavorite: true,
        sentAt: 1620318859000,
        url: null,
        replies: [{
            id: utilService.makeId(),
            from: 'alex207@gmail.com',
            body: 'Stop sending me spam e-mails! I dont have the time for you!!',
            sentAt: 1620318860000,
            url: 'https://i.gifer.com/7VE.gif',
        },
        ]
    },
    {
        id: utilService.makeId(),
        subject: '$10 tees?! Those end SOON.',
        from: 'newsletter@threadless.com',
        to: 'alex207@gmail.com',
        body: 'Sale prices as marked. $10 price only applies to Regular T-Shirts. Sale ends 5/7/21 at 9:59 AM CT. Excludes Cut and Sew T-Shirts, Artist Shops, Bucketfeet, and gift certificates.',
        isSend: false,
        isRead: false,
        isFavorite: true,
        sentAt: 1620315000000,
        url: null,
        replies: [{
            id: utilService.makeId(),
            from: 'alex207@gmail.com',
            body: 'Stop sending me spam e-mails! I dont have the time for you!!',
            sentAt: 1620318860000,
            url: 'https://s18670.pcdn.co/wp-content/uploads/WAT-Funny-Staff-Meeting_Feature.jpg',
        },
        ]
    },
    {
        id: utilService.makeId(),
        subject: 'Congratulate Nimrod for 3 years at...',
        from: 'notifications-noreply@linkedin.com',
        to: 'moshe123@gmail.com',
        body: 'Congratulate Nimrod Nir for 3 years at Samsung Israel R&D Center - SIRC,Congratulate Nofar Zimelman Avital and 4 others for starting new positions',
        isSend: false,
        isRead: false,
        isFavorite: true,
        sentAt: 1620314000000,
        url: null,
        replies: [{
            id: utilService.makeId(),
            from: 'alex207@gmail.com',
            body: 'Congratiulations maaaaaaaaaaaaan!!',
            sentAt: 1620318860000,
            url: 'https://i.gifer.com/VZvx.gif',
        },
        ]
    },
    {
        id: utilService.makeId(),
        subject: 'Incredible glasses shouldnt hurt your wallet.',
        from: 'zennioptical@mail.zennioptical.com',
        to: 'alex207@gmail.com',
        body: 'Incredible glasses shouldnt hurt your wallet, only on zenni.com!',
        isSend: false,
        isRead: false,
        isFavorite: true,
        sentAt: 1620313000000,
        url: 'https://static.zennioptical.com/marketing/campaign/iris_apfel/iris_video_preview-lg.jpg',
        replies: [{
            id: utilService.makeId(),
            from: 'alex207@gmail.com',
            body: 'Stop sending me spam e-mails! I dont have the time for you!!',
            sentAt: 1620318860000,
            url: 'https://i.gifer.com/3Ufn.gif',
        },
        ]
    },
    {
        id: utilService.makeId(),
        subject: 'Yu Kurosaki SENKO Firework-textured Nakiri & Slicer with Stylish Rosewood Handle',
        from: 'hocho-knife@hochoknife.com',
        to: 'alex207@gmail.com',
        body: 'Yu Kurosaki SENKO R2 Firework-textured Nakiri & Slicer with Stylish Rosewood Handle We are pleased to introduce Yu Kurosaki SENKO Nakiri (Vegetable Knife) & Sujihiki (Slicer) with Octagonal Brown-Ring Rosewood Handle.',
        isSend: false,
        isRead: false,
        isFavorite: true,
        sentAt: 1620312000000,
        url: 'https://store-attnwxa.mybigcommerce.com/product_images/uploaded_images/sakai-takayuki.jpeg',
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'GIFS ARE THE BEST YOOOOOOOO',
        from: 'alex207@gmail.com',
        to: 'mybestfriend@gmail.com',
        body: 'Heeeeeey man! check out this cool gif I found! I am collecting cool gifs so if you have any, please send them my way. Thanks! ',
        isSend: true,
        isRead: false,
        isFavorite: false,
        sentAt: 1620311000000,
        url: 'https://i.gifer.com/7VE.gif',
        replies: [{
            id: utilService.makeId(),
            from: 'alex207@gmail.com',
            body: 'Hey man, awesome GIF! I will send you any cool GIFS I find. Peace out, man.',
            sentAt: 1620312000000,
            url: 'https://i.gifer.com/WwaQ.gif',
        },
        ]
    },
    {
        id: utilService.makeId(),
        subject: 'HEY MAAAAN HOW ARE YOU????',
        from: 'alex207@gmail.com',
        to: 'mybestfriend@gmail.com',
        body: 'Where have you been all my life? I needed those tickets so bad... call me.',
        isSend: true,
        isRead: false,
        isFavorite: false,
        sentAt: 1620310000000,
        url: 'https://i.gifer.com/14Um.gif',
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'אלכסנדר, הוספנו תוכנית טלוויזיה שאולי תעניין אותך',
        from: 'info@mailer.netflix.com',
        to: 'alex207@gmail.com',
        body: 'כיתה קטלנית - לא שגרתי • אפל • נוער - סן פרנסיסקו, שנות ה-80. נער חסר בית מגויס לבית ספר פרטי שבו ילדים שגדלו במשפחות פשע לומדים כיצד להפוך למתנקשים חסרי רחמים',
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620300000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Movie suggestions',
        from: 'alex207@gmail.com',
        to: 'netflix@netflix.com',
        body: 'Hey I really like your Spanish movies, It would be great if you could make some more! Thanks in advance, Alex the Netflix Addict.',
        isSend: true,
        isRead: true,
        isFavorite: false,
        sentAt: 1620200000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Whoa! 254 people already ordered...',
        from: 'services01@aliexpress.com',
        to: 'alex207@gmail.com',
        body: 'Hi Alex Gordon, come grab the items you liked! Were you looking for this?',
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620190000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Tips to Speed Up Your Job Search',
        from: 'info@mail.glassdoor.com',
        to: 'alex207@gmail.com',
        body: 'Speed Up Your Job Search Position yourself for success with these five expert tips to help you speed up your job search. Gaps in Diversity & Inclusion How perception of workplace diversity & inclusion varies among employees of different racial and ethnic groups. Leaving a Safe Job Learn how to approach leaving a job you dont love during the pandemic. Glassdoor is committed to helping job seekers during COVID-19.',
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620180000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: '[Early Buy Best Price] Save 50% OFF! Redmi Note 10 Pro $299! Daily Snap Up Now>>',
        from: 'newsletter@deals.banggood.com',
        to: 'alex207@gmail.com',
        body: `Upgrade Gaming Chair $109.99! LED Projector Clock $15.99! Handheld Thermal Imager $109.99! - 135°Max Reclining + Rocking
        - Elastic sponge Backrest
        - Stereotype Cotton Seat Cushion
        - Removable Headrest & Lumbar Pillows
    	
          1/2" 800NM Electric Cordless Brushless Impact Wrench
        - 1/2" Square Drive
        - No-load Speed: 0~6200 RPM
        - Reverse Rotation Auto Stop Mode
        `,
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620170000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Prydwen Internal Mail: Maxson MX-001E DR-078',
        from: 'elder@maxson.com',
        to: 'alex207@gmail.com',
        body: "After we arrive in the Commonwealth, I want you to begin organizing sweep and retrieve teams. Take as many men as you need and coordinate the duty rosters with Lancer-Captain Kells. I want as much information about the energy readings from Danse's team as you can find. We could be on the brink of discovering the location of the Institute, so this needs to be your top priority.",
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620170000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Prydwen Internal Mail: Maxson MX-001E DR-092',
        from: 'elder@maxson.com',
        to: 'alex207@gmail.com',
        body: "Proctor Ingram is requesting any information that will assist her reconstruction efforts. I've passed along your gantry design to Kells, and we're both confident that it will be completed by the time her project is ready. We have a lot of resources riding on the success of Ingram's mission, so I expect you to help her in any way that you can.",
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620160000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Prydwen Internal Mail: Ingram IG-444PR DR-094',
        from: 'ingram@proctor.com',
        to: 'alex207@gmail.com',
        body: "I've sent over the proper forms to requisition two more scribes and you denied them? I don't need you slowing me down on this, Quinlan. Maxson keeps hounding me for results, but getting anything done with this project has been like trying to field-strip a laser rifle without using your hands. I need all the help I can get and if that means taking a few troops away from your scouting missions, I'm afraid you'll just have to make due. Now sign the damn forms, and let me do my job.",
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620150000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Prydwen Internal Mail: Neriah NR-490SS DR-112',
        from: 'neriah@prydwen.com',
        to: 'alex207@gmail.com',
        body: "I've checked the data three additional times to confirm and I'm positive that the DNA sample we have on file for Paladin Danse matches the DNA sample you provided. I'm not certain why you're having me do these readings, but I can assure you that my data is accurate. Could you at least tell me where the sample you found originated from?",
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620145000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Prydwen Internal Mail: Maxson MX-001E DR-124',
        from: 'ingram@proctor.com',
        to: 'alex207@gmail.com',
        body: "The information you've discovered regarding Danse is of a highly sensitive nature and we need to proceed carefully. Until I make a formal announcement to the crew, I need you to keep this quiet. I'll have Kells raise the alert to all departments shortly. In the meantime, I need every scrap of data your department can come up with regarding possible locations that Danse may have gone.",
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620145000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Prydwen Internal Mail: Maxson MX-001E DR-124',
        from: 'alex207@gmail.com',
        to: 'maxson@prydwen.com',
        body: "This is a priority alert. Paladin Danse has been identified as an Institute synth by our command staff. Its current whereabouts are unknown. If it's spotted, terminate immediately. Do not attempt to approach. If you are unable to engage, report Danse's last known location to any duty officer as soon as possible so we can track its movement. This attempt by the Institute to tear the Brotherhood down from the inside has failed. Despite their treachery, we will persevere and emerge victorious. Ad victoriam, brothers and sisters.",
        isSend: true,
        isRead: true,
        isFavorite: true,
        sentAt: 1620144000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Medical File DN-407P',
        from: 'alex207@gmail.com',
        to: 'maxson@prydwen.com',
        body: "Patient symptoms included inability to sleep and a 'dull throbbing pain in head.' All standard tests are negative. Evidence suggests post-traumatic stress disorder or similar issue. Until severity of issue increases, recommend voluntary removal from active duty. Patient was informed, but is currently in the field.",
        isSend: true,
        isRead: true,
        isFavorite: true,
        sentAt: 1620143000000,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Medical File DN-407P [Ongoing]',
        from: 'alex207@gmail.com',
        to: 'Knight-CaptainCade@prydwen.com',
        body: "Incident 1: Patient symptoms included inability to sleep and a 'dull throbbing pain in head.' All standard tests are negative. Evidence suggests post-traumatic stress disorder or similar issue. Until severity of issue increases, recommend voluntary removal from active duty. Patient was informed, but is currently in the field.Incident 2: Comparitive analysis of DNA data provided by Proctor Quinlan confirms subject is a synth. Subject not present for a full analysis. Suggest immediate termination of subject and preservation of remains for a full dissection/diagnostic.",
        isSend: true,
        isRead: true,
        isFavorite: true,
        sentAt: 1620142555550,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Medical File IG-444PR [Ongoing]',
        from: 'alex207@gmail.com',
        to: 'Knight-CaptainCade@prydwen.com',
        body: "Patient is complaining of phantom pain from limb loss. Previously prescribed painkiller and Stimpak mixture appears ineffective. Dosage has been increased to 300mg/day which is maximum allowable to remain duty-capable. Patient also describes nightmares of limb loss incident which is not unusual considering the level of trauma. Will continue to monitor.",
        isSend: true,
        isRead: true,
        isFavorite: true,
        sentAt: 1620142555450,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Medical File IG-444PR [Ongoing]',
        from: 'alex207@gmail.com',
        to: 'Knight-CaptainCade@prydwen.com',
        body: "Patient slipped and fell due to intoxication, causing minor laceration on forehead and contusion to upper chest. Applied Stimpak and recommended a minumum eight-hour bedrest. This is third intoxication-related medical incident for patient, so I ordered treatment program to begin, as per regulations.",
        isSend: true,
        isRead: true,
        isFavorite: true,
        sentAt: 1620142554550,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Medical File IG-444PR [Ongoing]',
        from: 'alex207@gmail.com',
        to: 'Knight-CaptainCade@prydwen.com',
        body: "Patient returned from patrol with critical injuries from exposure to nuclear warhead detonation. Injuries: left arm and leg missing, severe internal trauma, left hemisphere of head severely burned and acute radiation poisoning. Attempted emergency surgery, but patient died after three hours. Patient's remains were incinerated as per regulations.",
        isSend: true,
        isRead: true,
        isFavorite: true,
        sentAt: 1620142554350,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Medical File OG-133ES [Treated]',
        from: 'ingram@proctor.com',
        to: 'alex207@gmail.com',
        body: "Patient suffering from discoloration/rash, pustules and radioactive residue in groin area. Symptoms consistent with sexually-transmitted disease from GhoulIn-game spelling species. Patient treated and report has been sent to Proctor Ingram as per regulations.",
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620142554340,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Maxson MX-001E PM-097',
        from: 'maxson@proctor.com',
        to: 'alex207@gmail.com',
        body: "As we undertake our urgent mission in the Commonwealth, I feel that the mental well-being of the crew should remain a top priority for your department. I am well aware that being sequestered aboard this vessel can take its toll. If you observe any issues relating to the stresses that these lengthy missions can cause, I want you to treat it as though a legitimate illness is being reported. If we have any hope of defeating the Institute, we cannot afford to lose even a single soldier to mental instability.",
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620142554340,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Maxson MX-001E PM-099',
        from: 'ingram@proctor.com',
        to: 'alex207@gmail.com',
        body: "I've received your concerns about Proctor Ingram's condition, but I can assure you she is more than capable of handling herself. She's already proven to be an extremely valuable member of this crew, and I will not place her on mandatory leave until you've proven to me that she's physically incapable of handling her duties.",
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620142543340,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Teagan TG-477 PM-104',
        from: 'Teagan@proctor.com',
        to: 'alex207@gmail.com',
        body: "Our latest sweep and retrieve patrol came back with some medical supplies. If you have some extra time, head down to the cage and let me know what you want. If there's anything you don't need, I'll use it for trading. We're running a bit low on ammunition supplies, and these medical supplies are as good as caps with the locals.",
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620132553340,
        url: null,
        replies: []
    },
    {
        id: utilService.makeId(),
        subject: 'Kells KS-398LC PM-112',
        from: 'Lancer@proctor.com',
        to: 'alex207@gmail.com',
        body: "I've finished reading your medical report on Knight-Sergeant Merric. The fact that he managed to survive long enough to reach the Prydwen and deliver his report is absolutely incredible.  The sacrifice that he made for the sake of the mission is a testament to his dedication and loyalty. We will be holding a memorial service on the ship's forecastle at sunset this evening. I sincerely hope you'll be able to attend. ",
        isSend: false,
        isRead: false,
        isFavorite: false,
        sentAt: 1620042453340,
        url: null,
        replies: []
    },

];


export const mailDataService = {
    gMails,
}

